from fpdf import FPDF
import os
import io
from typing import Optional
from models import QuotationOutput
from services.dspy_groq import extract_quotation_data 

class ProfessionalPDF(FPDF):
    
    # COmpany detils
    COMPANY_NAME = "D Company"
    COMPANY_TAGLINE = "Innovating the Future of Service."
    BORDER_COLOR = (20, 90, 150)
    ACCENT_COLOR = (240, 240, 240)
    TEXT_COLOR = (0, 0, 0)

    def header(self):
        
        # Logo/Branding
        self.set_fill_color(*self.BORDER_COLOR)
        self.rect(0, 0, self.w, 20, 'F') 
        
        self.set_text_color(255, 255, 255) 
        self.set_font("Arial", "B", 24) 
        self.cell(0, 10, self.COMPANY_NAME, 0, 1, "L")
        
        self.set_font("Arial", "", 10) 
        self.cell(0, 5, self.COMPANY_TAGLINE, 0, 1, "L")
        self.ln(5)

    def footer(self):
        self.set_y(-15)
        self.set_font("Arial", "I", 8) 
        self.set_text_color(150, 150, 150) 
        self.cell(0, 5, f"Quotation Generated by {self.COMPANY_NAME}. Page {self.page_no()}/{{nb}}", 0, 0, "C")
        self.ln(4)
        self.cell(0, 5, "Address: Corporate Towers, Mumbai, India | Contact: +91 98765 43210", 0, 0, "C")

# --- 2. Price Cleaning Helper ---
def clean_price(price_str: str) -> float:
    price_str = price_str.upper().replace('INR', '').strip()
    price_value = 0.0
    
    try:
        cleaned_str = "".join(c for c in price_str if c.isdigit() or c == '.' or c == 'K')
        
        if 'K' in cleaned_str:
            numeric_part = float(cleaned_str.split('K')[0]) * 1000
        else:
            numeric_part = float(cleaned_str)
            
        price_value = numeric_part
    except (ValueError, IndexError, TypeError):
        pass 
        
    return price_value

def generate_quotation_pdf(data: QuotationOutput, output_filename: Optional[str] = "quotation.pdf") -> str:
    pdf = ProfessionalPDF("P", "mm", "A4")
    pdf.alias_nb_pages()
    pdf.add_page()
    pdf.set_text_color(*pdf.TEXT_COLOR) 
    pdf.set_font("Arial", "", 12) 
    
    # --- Quotation Title/Date ---
    pdf.set_y(30)
    pdf.set_font("Arial", "B", 18) 
    pdf.cell(0, 10, "PROPOSAL & QUOTATION", 0, 1, "L")
    pdf.set_font("Arial", "", 10) 
    pdf.cell(0, 5, f"Date: {data.quotation_date if data.quotation_date and data.quotation_date != 'Not Provided' else 'TBD'}", 0, 1, 'L')

    # --- Client Details Box ---
    pdf.ln(5)
    pdf.set_draw_color(*pdf.BORDER_COLOR)
    pdf.set_fill_color(245, 245, 255)
    pdf.set_line_width(0.5)
    pdf.rect(10, pdf.get_y(), 90, 30, 'DF')
    
    pdf.set_xy(12, pdf.get_y() + 2)
    pdf.set_font("Arial", "B", 12) 
    pdf.cell(0, 5, "BILLING TO:", 0, 1)
    
    pdf.set_x(12)
    pdf.set_font("Arial", "", 12) 
    pdf.cell(0, 5, data.client_name, 0, 1)
    
    if data.client_company:
        pdf.set_x(12)
        pdf.cell(0, 5, data.client_company, 0, 1)

    pdf.set_y(pdf.get_y() + 5)
    
    # --- Items Table Setup ---
    pdf.ln(10)
    
    # Define Column Widths
    col_widths = [10, 80, 30, 30, 40] 
    
    # Table Header
    pdf.set_font("Arial", "B", 10) 
    pdf.set_fill_color(*pdf.BORDER_COLOR)
    pdf.set_text_color(255, 255, 255)
    
    pdf.cell(col_widths[0], 10, "#", 0, 0, 'C', 1)
    pdf.cell(col_widths[1], 10, "Description", 0, 0, 'L', 1)
    pdf.cell(col_widths[2], 10, "Unit Price", 0, 0, 'R', 1)
    pdf.cell(col_widths[3], 10, "Qty", 0, 0, 'C', 1)
    pdf.cell(col_widths[4], 10, "TOTAL (INR)", 0, 1, 'R', 1)
    
    # Table Rows
    pdf.set_font("Arial", "", 10) 
    pdf.set_text_color(*pdf.TEXT_COLOR)
    pdf.set_draw_color(220, 220, 220)
    
    total_amount_inr = 0.0
    for i, item in enumerate(data.items):
        item_price_inr = clean_price(item.price)
        line_total = item_price_inr * item.quantity
        total_amount_inr += line_total
        
        pdf.set_fill_color(*pdf.ACCENT_COLOR)
        fill = i % 2 
        
        pdf.cell(col_widths[0], 8, str(i+1), 'LR', 0, 'C', fill)
        pdf.cell(col_widths[1], 8, item.name, 'R', 0, 'L', fill)
        pdf.cell(col_widths[2], 8, item.price, 'R', 0, 'R', fill) 
        pdf.cell(col_widths[3], 8, str(item.quantity), 'R', 0, 'C', fill)
        pdf.cell(col_widths[4], 8, f"INR {line_total:,.2f}", 'R', 1, 'R', fill) 
        
    pdf.cell(sum(col_widths), 0, "", "T", 1)

    # --- Calculations Summary ---
    GST_RATE = 0.18
    gst_amount = total_amount_inr * GST_RATE
    grand_total = total_amount_inr + gst_amount

    pdf.set_y(pdf.get_y() + 5)
    
    def print_summary_line(label, value, is_bold=False):
        style = 'B' if is_bold else ''
        pdf.set_font("Arial", style, 12)
        pdf.set_x(130) 
        pdf.cell(30, 7, label, 0, 0, 'R')
        pdf.cell(40, 7, f"INR {value:,.2f}", 0, 1, 'R')
        
    print_summary_line("Subtotal:", total_amount_inr)
    print_summary_line("GST (18%):", gst_amount)
    
    pdf.set_draw_color(0, 0, 0)
    pdf.set_line_width(0.4)
    pdf.line(160, pdf.get_y(), 200, pdf.get_y())
    
    pdf.ln(1)
    print_summary_line("GRAND TOTAL:", grand_total, is_bold=True)


    # --- Notes/Disclaimer ---
    if data.notes:
        pdf.ln(10)
        pdf.set_font("Arial", "B", 10) 
        pdf.cell(0, 5, "Special Instructions/Notes:", 0, 1)
        pdf.set_font("Arial", "", 10) 
        pdf.multi_cell(0, 5, data.notes)

    pdf.ln(15)
    pdf.set_font("Arial", "B", 10) 
    pdf.cell(0, 5, "Payment Terms: Due upon receipt. All prices are in Indian Rupees (INR).", 0, 1)
    
    # 💾 Output File
    pdf_path = os.path.join(os.getcwd(), output_filename)
    pdf.output(pdf_path) 
    
    return pdf_path

    # This output returns buffer for fast api to work 
    buffer = io.BytesIO()
    # 'S' tells FPDF to return the document as a byte string to the buffer
    pdf.output(buffer, 'S') 
    
    # Return the bytes content of the buffer
    return buffer.getvalue()


